language: node_js

node_js:
- node
- lts/boron
- lts/argon

before_script:
- yarn compile

before_deploy:
- yarn pack --filename package.tgz

deploy:
- provider: npm
  email: miton18
  api_key:
    secure: ka4Z3p4SR0hymAwSFKQsZgyN38AwO0rjTkd02SgiezeffoOpzsbomqafYH0hIe+wfoLMeUuHaKpxibXPiTkru4AxGcd2kMYv15lWbi53Ll/A3QSOi44LuYOafl1NC+k4m4Kf+dfv0s8Z2A0fVEouuvP374AMVRjZH4BlELmMCImrnsRMRvxX3C3XuuU1wHoWoW8jSNqMW7VmUyGWeZlXxTKEix71WAzxjjXiyGKNT8ysf4JnWzXva4zQ2ZwdvlAdYRs9ptAEWOkUStUY5eezT5yELY1kz3c8HuKgguHAJNIUBHrS5dc62sbt8R9fsweXbXob/COqYUOEb9Arlh59ZQ+wbPzAgoMzjM5OPVC/9r2zCuYclyYVm+4WLqgJgFYUpl0pLgC7afvwEDR0Yk3Z6wPa86jBaKB1AibY8xpNIu0cCbx5pjlq1Zlcx4up5TMKPZGEy2J+J0THk+GVZLi/BPBEX54JWnKSRcWy3YY0PdGYvp/6SYmCrALuKCfV1K7XP7Y83QlNtgD6P6pTtiHfuMJ5y0jVrAyWqrnILRHjBIKn21vCsMT9/SFemvDbtFjuZVVQvo7F9VxL1q0wjyZTxvr8BVNOjvFGAvftQ20XEKi6+IydDO8P3OkUpxVMgUbp2Om59dnYXES4X3N8Nn4RH0fHSbYLCWzlNvmlI/3KuLk=
  on:
    tags: true
    repo: starry-comet/comet-config

- provider: releases
  api_key:
    secure: Md2j6LNzbC4faDjxWBlBIygpxKKkvZT1ikNfxFNMLIZDMgR/kG3vDs65+GWsoq+PwrcwYYIM23P4AutrXWkMonspoIfE/aJM+dugBsukjHhXLOMn5ajjgGCXzkmJ1tofSZxj2BLQvH1khA8wNBSlNVxw5vokfJbmRfgtsKi4JgzAy/FXfoiwZvb3+PKoODwCDXyax43kgXz87AHydCsvd55ymktAoBhYf+JRby0vpKouwKRBb2ieQqk47rI+rATHURhq4FkoG8QFNIH3/zF7z7SHZBoVTZOMx6MpLJF9ngX7dtG8xiCj6rI+BeTXjVhGbMe3pNJnRKgi6pH1GR3j0CrEHPkmHIclaO1hwOl1cUobkvpfVmMgCgd8hQCHJXvzwJTXyWrAuJBjCK4tb0Rb1QATO0H7Sbw73WaIGOl0SF4ps3VIXG7wx09qtcqQg9gg2ZduxxBmlzSwKIfAq5niqZoAK234RWSObPFeUJV/HC96XemgsA6302sm3y21KVB/zV6YT53anFN2gdgx+wTCs/hcwSTC6LRHkk6t2oYfSmtKqxIUSSVoybJIUcxhzoOlXClOsu29UtsE2RYh8ZASZRosgtIelWphwtE9ALY4ZL3ZDswIRGVNN4NitKgk30ISUfY+PS/WFVo+kGRfT+xCxm+JOt8Ht7Yu8rV6hj5tKbo=
  file: package.tgz
  on:
    repo: starry-comet/comet-config
    tags: true
